### ISSUE TITLE
Add mounted hook/callback

### ISSUE THREAD

**Issue by tamb** [luwes/hyperstache#11]
At particular parts of compilation, could we add the ability to hook into the program? This could be useful for creating plugins.

Possible hooks:
Mounted
Compiled
Iteration lifecycles

**Comment by luwes** [comment]
thanks for the feedback, good idea!
did you have a specific use case in mind? some type of plugin?

**Comment by tamb** [comment]
I think being able to hook up `eventListener`s, maybe even a diffing algorithm into this.  Vanilla functionality.  Adding class names to specific iterations of DOM nodes.

**Comment by luwes** [comment]
@tamb I think this would would be better done after the process of Hyperstache.
Hyperstache doesn't look at the HTML. It's better done by a library similarly to HTM https://github.com/developit/htm which can be chained after Hyperstache.
See here, https://codesandbox.io/s/hyperstache-htm-ju83x

This does include Preact as well but, HTM converts the HTML string to `h()` calls

**Comment by tamb** [comment]
I think you're right. I cant wait to start using this.
