### ISSUE TITLE
Add comments `{{!comment}}`

### ISSUE THREAD

**Issue by luwes** [luwes/hyperstache#5]
https://handlebars-draft.knappi.org/guide/#template-comments

**Comment by AlexGustafsson** [comment]
I can take a look at this!

**Comment by luwes** [comment]
Awesome! would be great, thank you

good entry point would be adding an `else if` after this line I think
https://github.com/luwes/hyperstache/blob/master/src/build.js#L84

**Comment by luwes** [comment]
Implemented in #6 🎉
